#!/bin/sh
# crude script to allow bgpctl to be run interactively on a given rdomain
# this saves us from typing 'route -Tn exec bgpctl <command>' _every_single_time_

if [ ! -n "$1" ]; then
   echo "specify rdomain, e.g. '$0 1'"
   exit
fi

rdomain=$1
cmd=bgpctl

echo "running $cmd interactively in context of rdomain $rdomain"
echo "Type ^D to exit"

while printf '%s' "bgpctl > " ; read -r a; do
	route -T $rdomain exec $cmd $a
	printf '\n'
done

# we are nice, so we print a newline when exiting so the shell prompt isn't mangled
printf '\n'
