#!/bin/sh
# crude script to allow bgpctl to be run interactively on a given rdomain
# this saves us from typing 'bgpctl -s /var/run/bgpd.sock.N <command>' _every_single_time_

if [ ! -n "$1" ]; then
   echo "specify rdomain, e.g. '$0 1'"
   exit
fi

rdomain=$1
cmd="bgpctl -s /var/run/bgpd.sock.$1 "

echo "running bgpcl interactively in context of rdomain $rdomain"
echo "Type ^D to exit"

while printf '\n%s' "bgpctl > " ; read -r a; do
	$cmd $a
done

# we are nice, so we print a newline when exiting so the shell prompt isn't mangled
printf '\n'
